before_script:
    # Install dependencies
    - sh test/docker_install.sh > /dev/null
    - yarn

services:
  - mariadb:latest
  - postgres:alpine

variables:
    MYSQL_ROOT_PASSWORD: foo-bar-baz
    MYSQL_DATABASE: test
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    POSTGRES_DB: test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:6:
  image: node:6-alpine
  script: yarn run test

test:latest:
  image: node:alpine
  script: yarn run test
