language: node_js

node_js:
  - "0.11"
  - "0.10"

before_script:
  - psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS test;'
  - mysql -v -uroot test < ./tests/sql/mysql.sql
  - psql test postgres -f ./tests/sql/pgsql.sql