language: node_js
sudo: false

node_js:
  - "iojs"
  - "node"
  - "5.1"
  - "5.0"
  - "4.1"
  - "4.0"

before_script:
  - npm install -g gulp
  - psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS test;'
  - mysql -v -uroot test < ./test/sql/mysql.sql
  - psql test postgres -f ./test/sql/pgsql.sql

script: gulp

matrix:
  allow_failures:
    - node_js: iojs