language: node_js
sudo: false

node_js:
  - "node"
  - "5"
  - "4"

before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
  - psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS test;'
  - mysql -v -uroot test < ./test/sql/mysql.sql
  - psql test postgres -f ./test/sql/pgsql.sql

script: gulp

after_script:
  - CODECLIMATE_REPO_TOKEN=aa39789a53f6f8fd84747a98968c9f79795e890d55a533daa943b1042f81687f codeclimate-test-reporter < coverage/lcov.info